#!/usr/bin/env bash

set -u -o pipefail
shopt -s failglob

show_usage()
{
    echo "
  Usage: ${0##*/}

  Require xwininfo and byzanz-record.

  Click target window, wait until you hear a beep, then start recording.

  You can change DELAY environment variable to control the beep delay, it defaults to 5.

  All options are passed to byzanz-record
"
}

if { ! command -v xwininfo || ! command -v byzanz-record  ;} &>/dev/null ; then
    show_usage
    exit 1
fi

# get window geometry, don't use xdotool getwindowgeometry, there is a bug.
eval "$(\
    xwininfo | \
    awk '/^ *(Absolute|Width|Height)/ { $0 = gensub(/.* (.*): */, "\\1=", 1); print }' \
    )"

# beep before record
DELAY=${DELAY:-5}
while (( DELAY-- > 0 )) ; do
    printf '\r%3d' "$DELAY"
    sleep 1s
done
printf '\rrecording\n\a'

byzanz-record -x "$X" -y "$Y" -w "$Width" -h "$Height" --delay 0 "$@"
