#!/bin/bash

src_dir="$(realpath ~/plugged/misc/template/cpptt)"
dest_dir="$(mktemp -dp /tmp cpptt_XXXXXX)"

rsync -La --exclude="build/*/*/*" --exclude="tags" "$src_dir/" "$dest_dir"
cd "$dest_dir"
pwd

# cmake configuration is slow, i don't want to wait for it, but i need compile_commands.json
# for ycm to work. So i replace build path of existing compile_commands.json to the new one.
text=$(cat compile_commands.json)
echo "${text//"$src_dir"/"$dest_dir"}" > compile_commands.json

# the caller is responsible to call ./cmake.sh
# ./cmake.sh
