#!/usr/bin/env bash

set -eu -o pipefail

show_usage()
{
    echo "
  Usage: ${0##*/} <name pattern>

  Open html doc after cd to /var/www/html/doc.

  Use ./\$name*/index.html as path in find.

  Options:

    -h  Show this help.

    -f  Open as /... instead of http.
"
}

while getopts ":hw" opt; do
    case $opt in
        h)
            show_usage
            exit 0
            ;;

        * )
            echo -e "\n  Option does not exist : $OPTARG\n"
            usage; exit 1
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $# -lt 1 ]]; then
    show_usage
    exit 1
fi

name="$1"

cd /var/www/html/doc || exit 1

mapfile -d '' -t items < <(find -H ./* -maxdepth 2 -path "./$name*/index.html" -print0)

if [[ ${#items[@]} -eq 1 ]]; then
    google-chrome "http://localhost/doc/${items[0]#/var/html/doc/}"
elif [[ ${#items[@]} -eq 0 ]]; then
    >&2 echo "nothing found"
else
    printf "%s\n" "${items[@]#/var/www/html/doc/}"
    exit 1
fi

exit 0
