#!/usr/bin/env bash

set -o errexit
set -o nounset

prog_name=

show_usage()
{
    echo "Usage:"
    echo ""
    echo "    $prog_name"
    echo ""
    echo "    -h show this help"
}

while getopts ":h" opt; do
    case $opt in
        h)
            show_usage
            exit 0
            ;;

        * )
            echo -e "\n  Option does not exist : $OPTARG\n"
            usage; exit 1
            ;;
    esac
done
shift $((OPTIND-1))

template=~/.mkt_template/cpp_cmake

rsync -av "$template/.dedowsdi" .dedowsdi

exit 0
