#!/bin/bash

set -eu -o pipefail

template_path=~/.mkt_template
study_path=~/study

show_usage()
{
    echo "
  Usage: ${0##*/} TEMPLATE NAME

  Create test project under $study_path/year/month/day/.

  Options:
    -h           Show this help.

    -p           Create $study_path/year/month/day and print it.

    -l           List templates from ~/.mkt_template.
"
}


list_templates()
{
    find "$template_path" -maxdepth 1 -mindepth 1 -type d -printf "%f\n" | sort
}

# goto today's directory
today_dir="$study_path/$(date +"%Y/%m/%d")"
if [[ ! -d "$today_dir" ]]; then
    mkdir -p "$today_dir"
fi
cd "$today_dir"

while getopts "ht:pls:" opt; do
    case $opt in
        h)
            show_usage
            exit 0
            ;;

        p)
            pwd
            exit 0
            ;;

        l)
            list_templates
            exit $?
            ;;

        * )
            echo -e "\n  Option does not exist : $OPTARG\n"
            usage; exit 1
            ;;
    esac
done
shift $((OPTIND-1))

if (( $# < 2 )); then
    show_usage
    exit 1
fi

template=$1
dest=$2
src="$(realpath "$template_path/$template")"
if [[ ! -d "$src" ]]; then
    1>&2 echo "$src doesn't exists"
    return 1
fi

mkdir -p "${dest}"
rsync -a --exclude="build/*/*/*" --exclude="tags" --exclude="compile_commands.json" "$src/" "$dest"
cd "$dest" && pwd

exit $?
