#!/bin/bash

set -o errexit
set -o nounset

if [[ -z "$TMUX" ]]; then
    exit 1
fi

target=$(mkt "$@") || exit 1
winname="${target##*/}"
winid=$( tmux new-window -dPF '#{window_id}' -n "$winname" )

if [[ -f "$target" ]]; then
    cmd="cd \"$(mkt -p)\" && vim \"$target\""
elif [[ -d "$target" ]]; then
    cmd="cd \"$target\""

    # execute cmake if it exists
    if [[ -f "$target/script/cmake.sh" ]]; then

        # use usb shell to disable job control, no job message
        cmd="$cmd ; ( ./script/cmake.sh>cmake.log 2>&1 & ) "
    fi

    cmd="$cmd ; vim"
fi

tmux send-keys -t "$winid" "$cmd" Enter

# send switch command inside vim, avoid unnecessary blink
tmux send-keys -t "$winid" ":call system('tmux select-window -t $winid')" Enter

exit 0
