#!/usr/bin/env bash

set -eu -o pipefail

minimal=1

show_usage() {

    echo "
  Usage: ${0##*/} dir

  Create a new dir, init it as vim rtp.

  Options:
    -h  Show this help.
    -m  Miminal, add plugin, ftplugin and synax only.
    -M  Maximal, add everything.
    "
}

while getopts "hmM" opt; do
    case $opt in
        h)
            show_suage
            exit 0
            ;;
        m)
            minimal=1
            ;;
        M)
            minimal=0
            ;;

        * )
            echo -e "\n  Option does not exist : $OPTARG\n"
            usage; exit 1
            ;;
    esac
done
shift $((OPTIND-1))

rtp=${1:-}

if [[ -z "$rtp" ]]; then
    show_usage
    exit 1
fi

mkdir -p "$rtp" && cd "$rtp"

if [[ $minimal -eq 1 ]]; then
    mkdir -p autoload \
             ftplugin \
             plugin   \
             syntax
else
    mkdir -p autoload \
             colors   \
             compiler \
             doc      \
             ftplugin \
             indent   \
             keymap   \
             lang     \
             menu.vim \
             pack     \
             plugin   \
             print    \
             spell    \
             syntax   \
             tutor

    touch filetype.vim \
          scripts.vim
fi

exit 0
