#!/usr/bin/env bash

set -eu -o pipefail

show_usage()
{
    echo"
  Usage: ${0##*/} [<namespace>] <class>

  Browse openscenegraph doc

    -h  Show this help
"
}

while getopts ":hw" opt; do
    case $opt in
        h)
            show_usage
            exit 0
            ;;

        * )
            echo -e "\n  Option does not exist : $OPTARG\n"
            usage; exit 1
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $# -eq 0 ]]; then
    show_usage
    exit 1
fi

if [[ $# -eq 1 ]]; then
    namespace='\b\w+\b'
    class=$1
fi

if [[ $# -gt 1 ]]; then
    namespace=$1
    class=$2
fi

doc_path=${OSG_DOC-/var/www/html/doc/osg-doc}
class_path=${doc_path}/classes.html

if [[ ! -f "$class_path" ]]; then
    echo "$class_path doesn't exist"
    exit 1
fi

mapfile -t target_line < <(grep -iPo "\b\w+\.html\">$class<.*>$namespace<" "$class_path")

if [[ ${#target_line[@]} -gt 1 ]]; then
    echo "multiple target lines found:"
    printf "%s\n" "${target_line[@]}"
    exit 1
elif [[ ${#target_line[@]} -eq 0 ]]; then
    echo "nothing found"
    exit 1
fi

target_file=$(<<<"$target_line" grep -Po '^\w+\.html')

gvfs-open "$doc_path/$target_file"
