#!/bin/bash

rest=${DAILY_REST-"1m 10"}
work=${DAILY_WORK-"1m 45"}

if ! tmux has-session -t rest ; then
    tmux new-session -ds rest -n rest
    tmux send-keys -t rest "workrest $work $rest" 'Enter'
fi

if ! tmux has-session -t irc ; then
    tmux new-session -ds irc -n irc
    tmux send-keys -t irc "weechat" 'Enter'
fi

if ! tmux has-session -t work ; then
    tmux new-session -s work -n main
else
    tmux attach -t work
fi

# vim:set et ft=sh:
