#!/bin/bash

REST=${DAILY_REST-"30s 20"}
WORK=${DAILY_WORK-"1m 45"}

if ! tmux has-session -t rest ; then
    tmux new-session -ds rest -n clock
    tmux send-keys -t rest "workrest -w work -r $WORK $REST" 'Enter'
fi

if ! tmux has-session -t work ; then
    tmux new-session -s work -n main
else
    tmux attach -t work
fi

# vim:set et ft=sh:
