#!/bin/bash

if [[ -z "$TMUX" ]]; then
    exit 1
fi

if [[ $# -lt 1 ]]; then
    echo "it should be $0 template"
    exit 1
fi

template=$1
start_cmd=${2:-""}
test_dir="$(mkt -t "$template")"
winname="${test_dir##*/}"
winid=$( tmux new-window -dPF '#{window_id}' -n "$winname" )

tmux send-keys -t "$winid" \
    'MKT_DIR='"$test_dir"' && cd "$MKT_DIR" &&
    vim +'\'"$start_cmd"'
            call system("tmux select-window -t \"'$winid'\"")
            call job_start("bash -c \" [[ -f ./script/cmake.sh ]] &&./script/cmake.sh &> cmake.log\"")
         '\' 'Enter'

# vim need 0.18 second to start up, i don't want to switch to that window before
# vim starts.

exit 0
