#!/bin/bash

set -o errexit
set -o nounset

if [[ $# -lt 1 ]]; then
    >&2 echo "it should be $0 src_tt [dest_dir]"
    exit 1
fi

template=$1
template_path=$HOME/.tt_template
src_dir="$(realpath "$template_path/$template")"
dest_dir=${2:-$(mktemp -up ~/study/"$(date +"%Y/%m/%d")" "${template}_XXXXXX")}
mkdir -p "${dest_dir}"

if [[ ! -d "$src_dir" ]]; then
    >&2 echo "$src_dir does not exist"
    exit 1
fi

rsync -a --exclude="build/*/*/*" --exclude="tags" --exclude="compile_commands.json" "$src_dir/" "$dest_dir"
cd "$dest_dir" && pwd

exit 0
