#!/bin/bash

if [[ $# -lt 1 ]]; then
    >&2 echo "it should be $0 src_tt [dest_dir]"
    exit 1
fi

src_dir="$(realpath ~/plugged/misc/template/$1)"
dest_dir=${2:-$(mktemp -up /tmp cpptt_XXXXXX)}

if [[ ! -d "$src_dir" ]]; then
    >&2 echo "$src_dir does not exist"
    exit 1
fi

rsync -La --exclude="build/*/*/*" --exclude="tags" "$src_dir/" "$dest_dir"
cd "$dest_dir"
pwd

# cmake configuration is slow, i don't want to wait for it, but i need compile_commands.json
# for ycm to work. So i replace build path of existing compile_commands.json to the new one.
text=$(cat compile_commands.json)
echo "${text//"$src_dir"/"$dest_dir"}" > compile_commands.json

# the caller is responsible to call ./cmake.sh
# ./cmake.sh

exit 0
