#!/bin/bash

set -u -o pipefail

show_usage()
{
    echo "
  Usage: ${0##*/} [<work> <work_step> <rest> <rest_step>]

  Options:
    -h  Show this help.
"
}

if [[ -z $TMUX ]]; then
    echo "need tmux"
    exit 0
fi

work_session=work
rest_session=rest
work_step=${1-1m}
work_total_step=${2-45}
rest_step=${3-1m}
rest_total_step=${4-10}

while getopts ":hw:r:" Option ; do
    case $Option in

        h)
            show_usage
            exit 0
            ;;

        w)
            work_session="$OPTARG"
            ;;

        r )
            rest_session="$OPTARG"
            ;;

        *)
            echo "Unimplemented option:$Option"
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

tmux_wid="$(xdotool getactivewindow)"
# work_regular_style=$(tmux show-options -t work status-style)
work_regular_style='bg=green fg=black'
work_rest_style='bg=magenta fg=black'

# 0 as work, 1 as rest
stage=0

names=(work rest)
steps=("$work_step" "$rest_step")
total_steps=("$work_total_step" "$rest_total_step")
sessions=("$work_session" "$rest_session")

count=0

tmux set -t work status-style "$work_regular_style"
echo "${names[$stage]} begin, ${total_steps[stage]} * ${steps[stage]}"

while true ; do

    # update count
    sleep "${steps[$stage]}"
    count=$((count+1))

    # output count
    [[ $stage -eq 0 ]] && symbol='$$' || symbol='**'
    text="$symbol  $count / ${total_steps[$stage]}  $symbol"
    tput setaf $((RANDOM % 256)) ; figlet -ktc "$text"

    # set tmux status background to red for the last 2 steps
    if (( (count + 1) == total_steps[stage] && stage == 0 )); then
        tmux set -t work status-style "$work_rest_style"
    fi

    if (( count == total_steps[stage] )); then

        if (( stage == 0 )) ; then
            last_wid="$(xdotool getactivewindow)"
            xdotool windowactivate "$tmux_wid"
        else
            xdotool windowactivate "$last_wid" || xdotool windowactivate "$tmux_wid"
        fi

        echo "${names[$stage]} done"
        count=0
        stage=$((stage^1))

        # reset tmux status style
        if (( stage == 0 )); then
            tmux set -t work status-style "$work_regular_style"
        fi

        tmux switch-client -t "${sessions[$stage]}"
        echo "${names[$stage]} begin, ${total_steps[stage]} * ${steps[stage]}"

    fi
done
