#!/usr/bin/env bash

set -eu -o pipefail

show_usage()
{
    echo "
  Usage: ${0##*/}

  Init current dir as personal cpp project. All settings are copied into
  .dedowsdi directory.

  Options:
    -h  Show this help.
"
}

while getopts ":h" opt; do
    case $opt in
        h)
            show_usage
            exit 0
            ;;

        * )
            echo -e "\n  Option does not exist : $OPTARG\n"
            usage; exit 1
            ;;
    esac
done
shift $((OPTIND-1))

template=~/.mkt_template/cpp_cmake

rsync -av "$template/.dedowsdi" .dedowsdi

exit 0
