#!/usr/bin/env bash

set -eu -o pipefail

if [[ -z "$TMUX" ]]; then
    exit 1
fi

target=$(mkt "$@") || exit 1
winname="${target##*/}"
winid=$( tmux new-window -dPF '#{window_id}' -n "$winname" )

if [[ -f "$target" ]]; then
    cmd="cd \"$(mkt -p)\" && vim \"$target\""
elif [[ -d "$target" ]]; then
    cmd="cd \"$target\" ; if [[ -f CMakeLists.txt ]] ; then run_cmake ; fi ; vp "
fi

tmux send-keys -t "$winid" "$cmd" Enter

# send switch command inside vim, avoid unnecessary blink
tmux send-keys -t "$winid" ":call system('tmux select-window -t $winid')" Enter

exit 0
