#!/bin/bash

if [[ -z "$TMUX" ]]; then
    exit 0
fi

name="cpptt_$(head /dev/urandom | tr -cd [0-9a-zA-Z] | head -c 6)"
winid=$( tmux new-window -dPF '#{window_id}' -n "$name" )

tmux send-keys -t "$winid" 'cd $(cpptt | head -1) && vim main.cpp +'\''
    11
    call system("tmux select-window -t \"'"$winid"'\"")
    call job_start("bash -c \"./script/cmake.sh &> cmake.log\"")
    '\' 'Enter'

# vim need 0.18 second to start up, i don't want to switch to that window before vim starts.
#sleep 0.25

